// pages/tools.js
import { useState, useMemo } from 'react';
import Head from 'next/head';
import { useSheetData } from '../hooks/useSheetData';
import { groupByDate, getDailyStats, getOperatorStats, getIdleStreaks, getTodayStr } from '../lib/sheets';
import LastUpdated from '../components/LastUpdated';
import { LoadingSpinner, ErrorState } from '../components/Loading';
import { AlertTriangle, Users, FileText, Download, Copy, Check } from 'lucide-react';

function ToolCard({ icon: Icon, title, description, children }) {
  return (
    <div className="stat-card space-y-4">
      <div className="flex items-start gap-3">
        <div className="w-9 h-9 rounded-lg bg-[#1e1e1e] border border-[#2a2a2a] flex items-center justify-center shrink-0">
          <Icon size={16} className="text-[#c9a84c]" />
        </div>
        <div>
          <p className="font-body font-semibold text-[#f0ede8] text-sm">{title}</p>
          <p className="text-xs text-[#5a5a5a] mt-0.5">{description}</p>
        </div>
      </div>
      <div className="border-t border-[#1e1e1e] pt-4">
        {children}
      </div>
    </div>
  );
}

function csvDownload(filename, rows, headers) {
  const csv = [headers.join(','), ...rows.map(r => headers.map(h => `"${r[h] ?? ''}"`).join(','))].join('\n');
  const blob = new Blob([csv], { type: 'text/csv' });
  const url = URL.createObjectURL(blob);
  const a = document.createElement('a'); a.href = url; a.download = filename; a.click();
}

export default function Tools() {
  const { data, error, isLoading, refresh } = useSheetData();
  const [copied, setCopied] = useState(false);
  const [reportDate, setReportDate] = useState(() => {
    const [d, m, y] = getTodayStr().split('/');
    return `${y}-${m}-${d}`;
  });

  const idleStreaks = useMemo(() => getIdleStreaks(data), [data]);

  const today = getTodayStr();
  const todayData = data.filter(r => r.date === today);
  const todayStats = getDailyStats(todayData);

  // Operator monthly summary (current month data)
  const opMonthly = useMemo(() => {
    const now = new Date();
    const month = String(now.getMonth() + 1).padStart(2, '0');
    const year = now.getFullYear();
    const monthData = data.filter(r => {
      const [, m, y] = r.date.split('/');
      return m === month && y === String(year);
    });
    return getOperatorStats(monthData);
  }, [data]);

  // Daily report generator
  const reportData = useMemo(() => {
    const [y, m, d] = reportDate.split('-');
    const sheetDate = `${d}/${m}/${y}`;
    const dayData = data.filter(r => r.date === sheetDate);
    if (!dayData.length) return null;
    const stats = getDailyStats(dayData);
    const opStats = getOperatorStats(dayData);
    const top = opStats[0];
    const idlePct = Math.round((stats.idle / (stats.total || 1)) * 100);
    return { sheetDate, stats, opStats, top, idlePct };
  }, [data, reportDate]);

  const reportText = useMemo(() => {
    if (!reportData) return '';
    const { sheetDate, stats, opStats, top, idlePct } = reportData;
    const lines = [
      `MAA ASHISH — Daily Report`,
      `Date: ${sheetDate}`,
      `─────────────────────────`,
      `Total Rolls: ${stats.totalRolls}`,
      `Active Machines: ${stats.active} / ${stats.total}`,
      `Idle Machines: ${stats.idle} (${idlePct}%)`,
      `Operators on Floor: ${stats.operators.length}`,
      ``,
      `Top Operator: ${top?.name || '—'} (${top?.rolls || 0} rolls)`,
      ``,
      `Operator Summary:`,
      ...opStats.map(op => `  • ${op.name}: ${op.rolls} rolls across ${op.machines} machine(s)`),
      ``,
      idlePct > 40 ? `⚠ Alert: High idle rate today (${idlePct}%). Check machine availability.` : `✓ Idle rate is within normal range.`,
      `─────────────────────────`,
      `Generated by MAA Ashish Operations Dashboard`,
    ];
    return lines.join('\n');
  }, [reportData]);

  const handleCopy = () => {
    navigator.clipboard.writeText(reportText).then(() => {
      setCopied(true);
      setTimeout(() => setCopied(false), 2000);
    });
  };

  return (
    <>
      <Head><title>Tools — MAA Ashish</title></Head>
      <main className="max-w-7xl mx-auto px-4 sm:px-6 py-8 space-y-6">

        <div className="flex flex-col sm:flex-row sm:items-end justify-between gap-4">
          <div>
            <p className="text-xs font-mono uppercase tracking-widest text-[#c9a84c] mb-1">Utilities</p>
            <h1 className="font-display text-4xl text-[#f0ede8]">Tools</h1>
          </div>
          <LastUpdated onRefresh={refresh} isLoading={isLoading} />
        </div>

        {isLoading && <LoadingSpinner />}
        {error && <ErrorState message={error.message} onRetry={refresh} />}

        {!isLoading && !error && (
          <div className="grid md:grid-cols-2 gap-6">

            {/* Idle Streak Tracker */}
            <ToolCard
              icon={AlertTriangle}
              title="Idle Machine Tracker"
              description="Machines idle for 2+ consecutive days — check for maintenance needs"
            >
              {idleStreaks.length === 0 ? (
                <p className="text-sm text-[#5a5a5a] font-mono">No machines with extended idle streaks.</p>
              ) : (
                <>
                  <div className="space-y-0 mb-3 overflow-auto max-h-72">
                    <table className="w-full text-xs font-mono">
                      <thead>
                        <tr className="border-b border-[#1e1e1e]">
                          <th className="text-left py-2 text-[#5a5a5a]">Machine</th>
                          <th className="text-left py-2 text-[#5a5a5a]">Days Idle</th>
                          <th className="text-left py-2 text-[#5a5a5a]">Last Active</th>
                          <th className="text-left py-2 text-[#5a5a5a]">Last Operator</th>
                        </tr>
                      </thead>
                      <tbody>
                        {idleStreaks.map(s => (
                          <tr key={s.machine} className="border-b border-[#141414] hover:bg-[#1a1a1a]">
                            <td className="py-2 text-[#c9a84c]">#{s.machine}</td>
                            <td className="py-2 text-[#ef4444]">{s.streak}d</td>
                            <td className="py-2 text-[#888888]">{s.lastActive || '—'}</td>
                            <td className="py-2 capitalize text-[#888888]">{s.lastOp || '—'}</td>
                          </tr>
                        ))}
                      </tbody>
                    </table>
                  </div>
                  <button
                    onClick={() => csvDownload('idle-machines.csv', idleStreaks, ['machine', 'streak', 'lastActive', 'lastOp'])}
                    className="flex items-center gap-2 text-xs font-mono text-[#c9a84c] border border-[#c9a84c]/30 px-3 py-1.5 rounded hover:bg-[#c9a84c]/10 transition-all"
                  >
                    <Download size={12} /> Export CSV
                  </button>
                </>
              )}
            </ToolCard>

            {/* Operator Monthly Summary */}
            <ToolCard
              icon={Users}
              title="Operator Monthly Summary"
              description="This month's attendance, rolls, and performance per operator"
            >
              {opMonthly.length === 0 ? (
                <p className="text-sm text-[#5a5a5a] font-mono">No data for this month yet.</p>
              ) : (
                <>
                  <div className="overflow-auto max-h-72 mb-3">
                    <table className="w-full text-xs font-mono">
                      <thead>
                        <tr className="border-b border-[#1e1e1e]">
                          <th className="text-left py-2 text-[#5a5a5a]">Operator</th>
                          <th className="text-left py-2 text-[#5a5a5a]">Days</th>
                          <th className="text-left py-2 text-[#5a5a5a]">Total Rolls</th>
                          <th className="text-left py-2 text-[#5a5a5a]">Machines Used</th>
                        </tr>
                      </thead>
                      <tbody>
                        {opMonthly.map(op => (
                          <tr key={op.name} className="border-b border-[#141414] hover:bg-[#1a1a1a]">
                            <td className="py-2 capitalize text-[#f0ede8]">{op.name}</td>
                            <td className="py-2 text-[#888888]">{op.days}</td>
                            <td className="py-2 text-[#c9a84c]">{op.rolls}</td>
                            <td className="py-2 text-[#888888]">{op.machines || '—'}</td>
                          </tr>
                        ))}
                      </tbody>
                    </table>
                  </div>
                  <button
                    onClick={() => csvDownload('operator-monthly.csv', opMonthly, ['name', 'days', 'rolls', 'machines'])}
                    className="flex items-center gap-2 text-xs font-mono text-[#c9a84c] border border-[#c9a84c]/30 px-3 py-1.5 rounded hover:bg-[#c9a84c]/10 transition-all"
                  >
                    <Download size={12} /> Export CSV
                  </button>
                </>
              )}
            </ToolCard>

            {/* Daily Report Generator - full width */}
            <div className="md:col-span-2">
              <ToolCard
                icon={FileText}
                title="Daily Report Generator"
                description="Generate a text summary for any date — paste into WhatsApp or email"
              >
                <div className="space-y-4">
                  <div className="flex flex-wrap items-center gap-3">
                    <input
                      type="date"
                      value={reportDate}
                      onChange={e => setReportDate(e.target.value)}
                      className="px-3 py-1.5 bg-[#111] border border-[#222] rounded text-sm text-[#f0ede8] font-mono focus:outline-none focus:border-[#c9a84c]/50"
                    />
                    {reportData && (
                      <span className="text-xs text-[#3ecf6e] font-mono">✓ {reportData.stats.total} records found</span>
                    )}
                    {!reportData && reportDate && (
                      <span className="text-xs text-[#5a5a5a] font-mono">No data for selected date</span>
                    )}
                  </div>

                  {reportText && (
                    <>
                      <pre className="bg-[#0f0f0f] border border-[#1e1e1e] rounded p-4 text-xs font-mono text-[#888888] whitespace-pre-wrap leading-relaxed overflow-auto max-h-64">
                        {reportText}
                      </pre>
                      <button
                        onClick={handleCopy}
                        className="flex items-center gap-2 text-xs font-mono px-4 py-2 rounded transition-all bg-[#c9a84c]/10 border border-[#c9a84c]/30 text-[#c9a84c] hover:bg-[#c9a84c]/20"
                      >
                        {copied ? <><Check size={12} /> Copied!</> : <><Copy size={12} /> Copy Report</>}
                      </button>
                    </>
                  )}
                </div>
              </ToolCard>
            </div>

          </div>
        )}
      </main>
    </>
  );
}
